//FUNCTIONS FOR PROJECT
//Random Number Generator Function
const randomNumberGeneration = function (x) {
  //returns a randome number between 0 & (x - 1)
  return Math.floor(Math.random() * x);
};

//Random Letter Upper/Lower Case Generator Functions
function randomUpperCaseLetterGenerator() {
  const upperCase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  //Returns a random Cap letter (filtered from the above string)
  return upperCase[Math.floor(Math.random() * upperCase.length)];
}
function randomLowerCaseLetterGenerator() {
  const lowerCase = "abcdefghijklmnopqrstuvwxyz";
  //returns a random lower-case Letter (filtered from the above string)
  return lowerCase[Math.floor(Math.random() * lowerCase.length)];
}

//Array Randomizer Function
function randomArray(array) {
  //initiate variable = array length .. (number)
  let arrayLength = array.length;
  //initiate while loop (condition/expression)condition = while zero is NOT equal to array length ! expression >
  while (0 != arrayLength) {
    // generates random num between 0 - (arrayLength - 1) on each iteration
    let randomnum = Math.floor(Math.random() * arrayLength);
    //-= operator subtracts two values and assigns the resulting value to a variable
    arrayLength -= 1;
    //swap with current element
    let arrayindex = array[arrayLength]; // >> indexing last element & assigning to new variable
    array[arrayLength] = array[randomnum];
    array[randomnum] = arrayindex;
  }
  return array;
}

//TESTING ONE | DEVELOPERS CONSOLE TESTING !
const securityCodeGenerator = function (n1, n2, n3, n4, n5) {
  //Call Random Number Generator x 5
  const d1 = randomNumberGeneration(n1);
  const d2 = randomNumberGeneration(n2);
  const d3 = randomNumberGeneration(n3);
  const d4 = randomNumberGeneration(n4);
  const d5 = randomNumberGeneration(n5);
  console.log(`Digit 1 ${d1}`);
  console.log(`Digit 2 ${d2}`);
  console.log(`Digit 3 ${d3}`);
  console.log(`Digit 4 ${d4}`);
  console.log(`Digit 5 ${d5}`);
  //Confirm Random Numbers Generated by printing the below output to the developer console !
  console.log(`Random Digit Generation Completed Succesfully`);
  //Call Random UPPER-CASE Letter Generator !
  const L11 = randomUpperCaseLetterGenerator();
  console.log(`Letter 1 ${L11}`);
  console.log(`Random UPPER - CASE Letter generation completed succesfully`);
  //Call Random lower-case Letter Generator !
  const L22 = randomLowerCaseLetterGenerator();
  console.log(`Letter 2 ${L22}`);
  console.log(`Random lower-case Letter generation completed succesfully`);
  //Call Random UPPER-CASE Letter Generator !
  const L33 = randomUpperCaseLetterGenerator();
  console.log(`Letter 3 ${L33}`);
  console.log(`Random UPPER - CASE Letter generation completed succesfully`);
  //Initiate new array / explicit (manual) type conversion for specific sequential output
  newArray = [
    String(d1) +
      String(d2) +
      String(L22) +
      String(d3) +
      String(L33) +
      String(d4) +
      String(d5) +
      String(L11),
  ];
  //Call randomArray function (randomize items in array) on the newly generated array !
  Randomised = randomArray(newArray);
  //return the randomized array to the function
  return Randomised;
};
//TestingOne | Developers Console
const newCode = securityCodeGenerator(10, 20, 30, 40, 50);
console.log(`New Security Code : ${newCode}`);

//Testing Two | Goal > Cleaning Backend Code !
const securityCodeGenerator2 = function (n1, n2, n3, n4, n5) {
  //Call Random Number Generator x 5
  const d1 = randomNumberGeneration(n1);
  const d2 = randomNumberGeneration(n2);
  const d3 = randomNumberGeneration(n3);
  const d4 = randomNumberGeneration(n4);
  const d5 = randomNumberGeneration(n5);
  //Confirm Random Numbers Generated by printing the below output to the developer console !
  console.log(`Random Digit Generation Completed Succesfully`);
  //Call Random UPPER-CASE Letter Generator !
  const L11 = randomUpperCaseLetterGenerator();
  const L22 = randomLowerCaseLetterGenerator();
  const L33 = randomUpperCaseLetterGenerator();
  console.log(`Random Letter Generation Completed Succesfully`);
  //Initiate new array / explicit (manual) type conversion for specific sequential output
  newArray = [
    String(d1) +
      String(d2) +
      String(L22) +
      String(d3) +
      String(L33) +
      String(d4) +
      String(d5) +
      String(L11),
  ];
  //Call randomArray function (randomize items in array) on the newly generated array !
  Randomised = randomArray(newArray);
  //return the randomized array to the function
  return Randomised;
};
//Testing Two
const newCode2 = securityCodeGenerator2(10, 20, 30, 40, 50);
console.log(`New Security Code ${newCode2}`);
